name = "Rsvg"
uuid = "c4c386cf-5103-5370-be45-f3a111cca3b8"
version = "0.3.0-DEV"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"

[compat]
julia = "1"
Cairo = "0.8"
BinaryProvider = "0.5.5"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
