name = "Rsvg"
uuid = "c4c386cf-5103-5370-be45-f3a111cca3b8"
version = "0.3.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
Librsvg_jll = "925c91fb-5dd6-59dd-8e8c-345e74382d89"

[compat]
julia = "1.3"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
